name = "game-events-api"
main = "dist/worker.js"
compatibility_date = "2024-07-20"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "KV_EVENTS", id = "34e594675b1c475194b1d22c7706c821" }
]

[build]
command = "npm run build"
outdir = "dist"

[dev]
port = 8787
ip = "localhost"