name = "events-web-worker"
main = "workers/events/geo.js"
compatibility_date = "2025-07-05"

# KV 存储配置
kv_namespaces = [
  { binding = "EVENTS_KV", id = "your-kv-namespace-id" }
]

# 路由配置 (生产环境使用)
routes = [
  { pattern = "api/events/geo", zone_name = "yourdomain.com" }
]

# 开发环境配置
[dev]
ip = "localhost"
port = 8787
